version: '3.9'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./server
    env_file:
      - ./server/.env       # Reads MONGODB_URI and other backend variables
    ports:
      - "5000:5000"
    depends_on:
      - ai_engine
    environment:
      - AI_ENGINE_URL=http://ai_engine:8000
      # Additional overrides can go here
    restart: always

  ai_engine:
    build: ./ai_engine
    env_file:
      - ./ai_engine/.env    # AI engine environment variables
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: always
