version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: prepsmart-project-mongo
    restart: unless-stopped
    volumes:
      - prepsmart-project_mongo_data:/data/db
    ports:
      - "27017:27017"

  ai_engine:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    container_name: prepsmart-project-ai_engine
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./ai_engine/uploads:/app/uploads

  backend:
    build:
      context: ./backend
    container_name: prepsmart-project-backend
    restart: unless-stopped
    depends_on:
      - mongo
      - ai_engine
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: prepsmart-project-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  prepsmart-project_mongo_data:
