version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: prepsmart-project-mongo
    restart: unless-stopped
    volumes:
      - prepsmart-project_mongo_data:/data/db
    ports:
      - "27017:27017"

  ai_engine:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    container_name: prepsmart-project-ai_engine
    restart: unless-stopped
    depends_on:
      - mongo
    expose:
      - "8000"
    volumes:
      - ./ai_engine/uploads:/app/uploads

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prepsmart-project-backend
    restart: unless-stopped
    depends_on:
      - mongo
      - ai_engine
    expose:
      - "5000"
    environment:
      - PORT=5000

  nginx:
    image: nginx:alpine
    container_name: prepsmart-project-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - ai_engine
    ports:
      - "80:80"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  prepsmart-project_mongo_data:
