version: '3.9'

services:
  # ------------------------------
  # Frontend React app
  # ------------------------------
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_API_URL=/api

  # ------------------------------
  # Node.js Backend
  # ------------------------------
  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - ai_engine
      - mongo
    environment:
      - AI_ENGINE_URL=http://ai_engine:8000
      - MONGODB_URI=mongodb://mongo:27017/prepsmart
    restart: always

  # ------------------------------
  # AI Engine (Flask)
  # ------------------------------
  ai_engine:
    build: ./ai_engine
    env_file:
      - ./ai_engine/.env
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - backend
      - mongo
    restart: always

  # ------------------------------
  # MongoDB Database
  # ------------------------------
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

# ------------------------------
# Volumes
# ------------------------------
volumes:
  mongo_data:
