version: '3.9'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_API_URL=/api

  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - ai_engine
      - mongo
      - ollama
    environment:
      - AI_ENGINE_URL=http://ai_engine:8000
      - OLLAMA_URL=http://ollama:11434
      - MONGODB_URI=mongodb://mongo:27017/prepsmart
    restart: always

  ai_engine:
    build: ./ai_engine
    env_file:
      - ./ai_engine/.env
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:11434 || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  ollama_data:
